CREATE TABLE "GCG_INS_DETAIL" PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL_NUMBER" CHAR(20),
 "TASK" CHAR(200),
 "TASKID" CHAR(2),
 "PERSON_RESP" CHAR(50),
 "REFER_TO" CHAR(50),
 "EMPID" CHAR(50),
 "INSP_DATE" DATE,
 "SER_MES_DEV" CHAR(50),
 "ACTUAL_MEASURE" CHAR(50) );
