CREATE TABLE "GCG_INS_HEADERB" PAGESIZE=4096 (
 "TESTPLAN" CHAR(50),
 "INSTALL" CHAR(1),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL_NUMBER" CHAR(20),
 "BENCH" CHAR(50),
 "START_DATE" DATE,
 "REV" CHAR(20),
 "NOTES" CHAR(200) );
